# Generated by Django 3.1 on 2020-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_converter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_icon',
            field=models.ImageField(blank=True, upload_to='icons/%d/%m/%Y'),
        ),
    ]
