# Generated by Django 3.1 on 2020-08-24 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_converter_app', '0002_ingredient_ingredient_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_icon',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
