# Generated by Django 3.1 on 2020-08-24 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_converter_app', '0003_auto_20200824_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
